.github/workflows/default_release_callable.yml
.github/workflows/default_release_dry_run_callable.yml
.github/workflows/maven_release_callable.yml
.github/workflows/maven_release_dry_run_callable.yml
.github/workflows/this_linter.yml
.github/workflows/this_pull_request.yml
.github/workflows/this_release.yml
.github/workflows/this_release_dry_run.yml
.github/workflows/this_renovate_auto_approve.yml
.github/workflows/this_slash_ops_command_help.yml
.github/workflows/this_slash_ops_comment_dispatch.yml
.github/workflows/this_spelling.yml
.github/workflows/this_stale.yml
.github/workflows/this_welcome_message.yml
setup-workflows.sh

... doesn't work without a version number: 
```
Invalid workflow file: .github/workflows/this_welcome_message.yml#L13
invalid value workflow reference: no version specified
```

fix: reference the `main` workflow version

---

update-workflows.sh

- use correct indentation if a `yamllint` ignore is generated --> produce a valid Yaml file
- do not copy `release_*` workflows --> there are none
Verified with the templates for Docker repositories.

fix: fix indentation of `yamlint` ignore

---

.release_github_only_auto/package-lock.json
.release_github_only_auto/package.json
.release_maven_auto/package-lock.json
.release_maven_auto/package.json

What you see is what you get. Fix the version numbers to be sure what dependencies are used creating a release. As we have Renovate running, updates are no problem.
Manually verified the GitHub only workflow in the test repository.

fix: use exact version numbers for release dependencies

---

.github/workflows/terraform_module_terraform_callable.yml

Correct the names of the secrets needed by TfLint. The projects automatically have access to `TFLINT_ROLE_ARN` and `TFLINT_AWS_REGION`. Using non-existing secrets ends with `Secret AWS_TFLINT_ROLE_ARN is required, but not provided while calling.`
Copy & paste of the secret names from the settings page.

fix: correct names for secrets used by TfLint

---

.github/workflows/terraform_module_terraform_callable.yml

TfLint can't be installed in the workflow as the version number contains the `v` prefix which was added manually before. We simply remove the prefix here.
```
tflint_version="v0.50.3"
curl -o tflint.zip -L \
[https://github.com/terraform-linters/tflint/releases/download/v${tflint_version}/tflint_linux_amd64.zip](https://github.com/terraform-linters/tflint/releases/download/v$%7Btflint_version%7D/tflint_linux_amd64.zip)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     77      0 --:--:-- --:--:-- --:--:--    78
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it …
```

ci: remove version prefix for TfLint installation

---

.github/workflows/default_welcome_message_callable.yml

Currently, the welcome message is commented to every PR, even ones that were opened by renovate. The message itself does not make sense on PRs opened by bots and this PR fixes that behavior.
It also fixes a link at the end of the message to the location of the workflow file that generated the message.
None.

fix: only comment welcome message on non-bot user PRs

---

update-workflows.sh

When we update the workflows with `update_workflows.sh` a PR is automatically created. But the description of it didn't follow our own template. This PR adds a multiline description with `Description` and `Verification` section.
None.

fix: create the PR according to our own standards

---

update-workflows.sh

The `head` of the default branch might not be tagged, i.e. `ci` commit, ... We now find the latest tag in the commit history to be able to create the comment when updating the workflows.
Locally.

fix: find the nearest tag for workflow updates

---

update-workflows.sh

The script didn't consume the release type which is following the `--release-type` parameter. Thus it always failed if the parameter was given.
Tested locally.

fix: read the release-type parameter when updating the workflows

---

.github/workflows/default_linter_callable.yml

Configures the Json linter to use the specified files only. Otherwise all Json files are checked, including Json5, which does not work.
Job manually tested in the test repository.

fix: check added or modified Json files only

---

update-workflows.sh

The automatically created PR looked like
```
Text here
```
which is wrong. The reason is, that `<<-` removes tabs only {and not spaces} and the IDE converts tabs into spaces automatically.
Checked the output on my machine.

fix: remove indentation from PR text

---

README.md
update-workflows.sh

This PR copies the `.config` directory to the destination. It contains configuration files for our workflows.
Manually verified on my local machine.

fix: copy the `.config` directory

---

.github/update_workflows.sh

All `Repository-Template-*` repositories reference this script as `.github/update_workflows.sh`. We move the script to the correct location and provide an update mechanism in case the script is found in the wrong directory.
Verified on my local machine.

fix: move update script to correct location

---

update-workflows.sh

Running the update script multiple times results in `branch already exists` errors. Deleting the branch before is not an option, as we may loose the work on that branch. This PR adds the current timestamp to the branch name to make it unique.
Manually tested on my local machine.

fix: use unique branch names in destination repository

---

.github/workflows/default_slash_ops_command_ready_callable.yml

`/ready` prepares the PR for the review. Thus we should also remove the HTML comments from the PR body, usually Yamllint disable statements.

feat: remove HTML comments from pull request body

---

.config/dictionaries/project.txt
.config/dictionaries/workflow.txt
update_workflows.sh

Moves `conventionalcommits` to the internal dictionary as it is not copied to the target repository.

fix: use the correct dictionary

---

.config/dictionaries/project.txt
.config/dictionaries/workflow.txt
.github/workflows/scripts/check_dictionaries.sh
.gitignore
README.md
simulate.sh
update_workflows.sh

Adds `simulate.sh` to execute the workflow update in a temporary repository. This makes it possible to check the output of the script and determine the correct wordlist for the dictionary.
Script locally tested.

feat: add script to simulate the update

---

.config/dictionaries/project.txt
.config/dictionaries/workflow.txt
.github/CODE_OF_CONDUCT.md
update_workflows.sh

Adds the code of conduct and contribution guideline as these files are identical for all projects.

feat: add code of conduct and contribution guideline

---

.config/dictionaries/project.txt
.github/workflows/default_spelling_callable.yml
.github/workflows/scripts/check_dictionaries.sh
.github/workflows/this_spelling.yml
.gitignore
simulate.sh

As we have several dictionaries we want to ensure that a word does not appear in multiple dictionaries to keep them clean.
Also fixes:
- there is no prefix in NPM version numbers, so don't try to remove it as npm then can't install the requested version.
- always run the dictionary validation. Every change to the repository can result in orphaned words.

feat: do not allow duplicates in all dictionaries

---

.github/workflows/scripts/check_dictionaries.sh

We saw failing workflows complaining about
```
Checking for orphaned words in dictionary: .config/dictionaries/project.txt
The following word in the .config/dictionaries/project.txt dictionary is not being used: (boto)
The following word in the .config/dictionaries/project.txt dictionary is not being used: (botocore)
```
Not removing the `dictionaryDefinitions` resolves the problem, but I don't know, why. It seems that CSpell is working differently. Having `dictionaryDefinitions` without `dictionaries` shouldn't make a difference as `dictionaries` activates the usage of the definitions.

fix: validate the dictionaries correctly

---

README.md
update_workflows.sh

Add the option to update an existing branch with the updated workflows. Nice if you want to reuse the monthly Renovate MR.

feat: add --use-existing-branch option to update_workflows.sh

---

update_workflows.sh

The script always fails silently when using `--use-existing-branch`. We removed 2 parameters from the stack, but there is only 1.

fix: do not remove a second option from the parameter stack for `--use-existing-branch`

---

.config/dictionaries/workflow.txt
.github/workflows/terraform_module_terraform_callable.yml

Make the minimum Terraform version in the Workflows configurable by the user. It is not always possible to check against v1.0.0, especially if features from newer versions are used. The workflow fails in such cases.

feat: make the minimum Terraform version configurable

---

.github/renovate.json5

Set the correct title for pull requests generated by Renovate.
Standard workflow files should be updated with `ci: `, but the code we develop in this repository should show a `chore: ` as these files live in `.github/workflows` but are not directly used.

chore: set correct `semanticCommitType` for Renovate updates

---

.github/workflows/python_pypi_publish_callable.yml

Checking PyPi I found out that there was only one release available. The problem is the version number in setup.cfg which was not incremented. This PR extracts the version number from the current tab and replaces the version number in setup.cfg.

fix: set the version number in setup.cfg
